from __future__ import annotations

from decimal import Decimal

from app.modules.catalog.application.schemas import (
    BrandCreateRequest,
    CategoryCreateRequest,
    ProductCreateRequest,
    ProductMediaPayload,
    ProductVariantPayload,
)

SEED_CATEGORIES: list[CategoryCreateRequest] = [
    CategoryCreateRequest(name="Women Ethnic", slug="women-ethnic"),
    CategoryCreateRequest(name="Women Western", slug="women-western"),
    CategoryCreateRequest(name="Men Fashion", slug="men-fashion"),
    CategoryCreateRequest(name="Beauty & Personal Care", slug="beauty-personal-care"),
    CategoryCreateRequest(name="Jewellery & Accessories", slug="jewellery-accessories"),
    CategoryCreateRequest(name="Home Decor", slug="home-decor"),
    CategoryCreateRequest(name="Footwear", slug="footwear"),
    CategoryCreateRequest(name="Bags", slug="bags"),
]

SEED_BRANDS: list[BrandCreateRequest] = [
    BrandCreateRequest(name="Aarika", slug="aarika"),
    BrandCreateRequest(name="GlowNest", slug="glownest"),
    BrandCreateRequest(name="UrbanStitch", slug="urbanstitch"),
    BrandCreateRequest(name="Cosmix", slug="cosmix"),
    BrandCreateRequest(name="Veloura", slug="veloura"),
    BrandCreateRequest(name="HouseBloom", slug="housebloom"),
]


def seed_product(
    *,
    category_id: str,
    brand_id: str,
    name: str,
    slug: str,
    short_description: str,
    description: str,
    variant_name: str,
    sku: str,
    price: str,
    quantity_available: int,
    image_seed: str,
) -> ProductCreateRequest:
    return ProductCreateRequest(
        category_id=category_id,
        brand_id=brand_id,
        name=name,
        slug=slug,
        short_description=short_description,
        description=description,
        is_published=True,
        variants=[
            ProductVariantPayload(
                name=variant_name,
                sku=sku,
                price=Decimal(price),
                quantity_available=quantity_available,
                is_default=True,
            )
        ],
        media=[
            ProductMediaPayload(
                media_url=f"https://picsum.photos/seed/{image_seed}/640/840",
                alt_text=name,
                sort_order=1,
            )
        ],
    )


SEED_PRODUCTS: list[ProductCreateRequest] = [
    seed_product(
        category_id="women-ethnic",
        brand_id="aarika",
        name="Floral Festive Kurta Set",
        slug="floral-festive-kurta-set",
        short_description="Printed rayon kurta set with dupatta",
        description="Easy festive dressing with soft rayon fabric, coordinated pants, and a lightweight dupatta.",
        variant_name="M / Pink",
        sku="KURTA-FLORAL-PNK-M",
        price="899.00",
        quantity_available=48,
        image_seed="floral-kurta",
    ),
    seed_product(
        category_id="women-ethnic",
        brand_id="aarika",
        name="Embroidered Anarkali Gown",
        slug="embroidered-anarkali-gown",
        short_description="Party-ready anarkali with rich embroidery",
        description="A flowy anarkali silhouette designed for wedding events and festive evenings.",
        variant_name="L / Wine",
        sku="ANARKALI-WINE-L",
        price="1299.00",
        quantity_available=31,
        image_seed="anarkali-gown",
    ),
    seed_product(
        category_id="women-ethnic",
        brand_id="aarika",
        name="Pastel Saree With Border",
        slug="pastel-saree-with-border",
        short_description="Soft saree with elegant contrast border",
        description="Lightweight drape with an understated festive finish for everyday celebrations.",
        variant_name="Free Size / Mint",
        sku="SAREE-PASTEL-MINT-FS",
        price="999.00",
        quantity_available=44,
        image_seed="pastel-saree",
    ),
    seed_product(
        category_id="women-ethnic",
        brand_id="aarika",
        name="Mirror Work Lehenga Set",
        slug="mirror-work-lehenga-set",
        short_description="Statement lehenga with mirror detailing",
        description="Celebration-ready lehenga set designed for wedding functions and festive dressing.",
        variant_name="M / Coral",
        sku="LEHENGA-MIRROR-CORAL-M",
        price="1799.00",
        quantity_available=18,
        image_seed="mirror-lehenga",
    ),
    seed_product(
        category_id="women-western",
        brand_id="veloura",
        name="Ribbed Crop Top Combo",
        slug="ribbed-crop-top-combo",
        short_description="Stretch cotton crop tops pack of 3",
        description="A soft everyday combo set designed for layering, college wear, and casual styling.",
        variant_name="Free Size / Multi",
        sku="CROP-COMBO-MULTI-FS",
        price="499.00",
        quantity_available=76,
        image_seed="crop-top-combo",
    ),
    seed_product(
        category_id="women-western",
        brand_id="veloura",
        name="Minimal Satin Shirt Dress",
        slug="minimal-satin-shirt-dress",
        short_description="Glossy shirt dress for brunch and outings",
        description="Relaxed satin shirt dress with a clean collar line and elegant drape.",
        variant_name="S / Beige",
        sku="SATIN-DRESS-BEIGE-S",
        price="1049.00",
        quantity_available=22,
        image_seed="satin-shirt-dress",
    ),
    seed_product(
        category_id="women-western",
        brand_id="veloura",
        name="Pleated Co-ord Lounge Set",
        slug="pleated-coord-lounge-set",
        short_description="Monotone co-ord set with relaxed pleats",
        description="An easy matching set with a polished silhouette for daily wear and travel.",
        variant_name="L / Stone",
        sku="COORD-PLEATED-STONE-L",
        price="1199.00",
        quantity_available=27,
        image_seed="pleated-coord",
    ),
    seed_product(
        category_id="women-western",
        brand_id="veloura",
        name="Cotton Oversized Graphic Tee",
        slug="cotton-oversized-graphic-tee",
        short_description="Relaxed tee with minimal front graphic",
        description="Soft cotton oversized tee that works well for streetwear and everyday layering.",
        variant_name="XL / White",
        sku="TEE-GRAPHIC-WHT-XL",
        price="579.00",
        quantity_available=63,
        image_seed="graphic-tee",
    ),
    seed_product(
        category_id="men-fashion",
        brand_id="urbanstitch",
        name="Classic Oversized Polo Tee",
        slug="classic-oversized-polo-tee",
        short_description="Relaxed fit polo tee for streetwear looks",
        description="An oversized cotton polo designed for all-day comfort with a clean collar finish.",
        variant_name="XL / Navy",
        sku="POLO-TEE-NAVY-XL",
        price="699.00",
        quantity_available=40,
        image_seed="polo-tee",
    ),
    seed_product(
        category_id="men-fashion",
        brand_id="urbanstitch",
        name="Textured Casual Shirt",
        slug="textured-casual-shirt",
        short_description="Summer-ready shirt with subtle texture",
        description="An easy casual shirt with a breathable weave and versatile neutral tone.",
        variant_name="L / Olive",
        sku="TEXTURE-SHIRT-OLIVE-L",
        price="849.00",
        quantity_available=29,
        image_seed="textured-shirt",
    ),
    seed_product(
        category_id="men-fashion",
        brand_id="urbanstitch",
        name="Slim Fit Cargo Trouser",
        slug="slim-fit-cargo-trouser",
        short_description="Utility-inspired trouser with tapered fit",
        description="Street-ready cargo trouser with practical pockets and a clean everyday shape.",
        variant_name="34 / Charcoal",
        sku="CARGO-TRS-CHR-34",
        price="1099.00",
        quantity_available=25,
        image_seed="cargo-trouser",
    ),
    seed_product(
        category_id="men-fashion",
        brand_id="urbanstitch",
        name="Everyday Linen Blend Shirt",
        slug="everyday-linen-blend-shirt",
        short_description="Breathable shirt for work and weekends",
        description="Minimal linen blend shirt with a refined collar and soft hand feel.",
        variant_name="M / Sky",
        sku="LINEN-SHIRT-SKY-M",
        price="949.00",
        quantity_available=33,
        image_seed="linen-shirt",
    ),
    seed_product(
        category_id="beauty-personal-care",
        brand_id="glownest",
        name="Hydra Glow Serum",
        slug="hydra-glow-serum",
        short_description="Niacinamide serum for daily glow",
        description="A lightweight facial serum made for brightening, smoothing, and everyday hydration.",
        variant_name="30 ml",
        sku="SERUM-HYDRA-30ML",
        price="349.00",
        quantity_available=95,
        image_seed="hydra-serum",
    ),
    seed_product(
        category_id="beauty-personal-care",
        brand_id="glownest",
        name="Cocoa Body Lotion",
        slug="cocoa-body-lotion",
        short_description="Nourishing body lotion with cocoa butter",
        description="A non-sticky lotion designed to leave skin soft, moisturized, and lightly scented.",
        variant_name="250 ml",
        sku="LOTION-COCOA-250ML",
        price="299.00",
        quantity_available=88,
        image_seed="body-lotion",
    ),
    seed_product(
        category_id="beauty-personal-care",
        brand_id="cosmix",
        name="Velvet Matte Lipstick Set",
        slug="velvet-matte-lipstick-set",
        short_description="Everyday matte lip colors set of 4",
        description="Long-wear matte shades curated for daily wear and special occasions.",
        variant_name="Set of 4",
        sku="LIP-MATTE-SET4",
        price="399.00",
        quantity_available=56,
        image_seed="lipstick-set",
    ),
    seed_product(
        category_id="beauty-personal-care",
        brand_id="glownest",
        name="Rice Water Face Cleanser",
        slug="rice-water-face-cleanser",
        short_description="Gentle cleanser with clean-rinse finish",
        description="A daily face wash crafted for balanced cleansing without stripping moisture.",
        variant_name="100 ml",
        sku="CLNSR-RICE-100ML",
        price="259.00",
        quantity_available=74,
        image_seed="face-cleanser",
    ),
    seed_product(
        category_id="beauty-personal-care",
        brand_id="cosmix",
        name="Spa Hair Oil",
        slug="spa-hair-oil",
        short_description="Herbal nourishment oil for weekly care",
        description="A soothing blend for scalp massage and soft, healthy-looking hair.",
        variant_name="200 ml",
        sku="HAIR-OIL-SPA-200ML",
        price="329.00",
        quantity_available=67,
        image_seed="spa-hair-oil",
    ),
    seed_product(
        category_id="jewellery-accessories",
        brand_id="veloura",
        name="Layered Gold-Plated Necklace",
        slug="layered-gold-plated-necklace",
        short_description="Minimal layered necklace for festive styling",
        description="A lightweight statement necklace that pairs easily with western and ethnic looks.",
        variant_name="One Size / Gold",
        sku="NECK-LAYER-GOLD-OS",
        price="279.00",
        quantity_available=61,
        image_seed="layered-necklace",
    ),
    seed_product(
        category_id="jewellery-accessories",
        brand_id="veloura",
        name="Statement Jhumka Pair",
        slug="statement-jhumka-pair",
        short_description="Detailed jhumkas with festive shine",
        description="Classic party jhumkas with a bright finish and wearable weight.",
        variant_name="One Size / Gold",
        sku="JHUMKA-STATEMENT-OS",
        price="199.00",
        quantity_available=83,
        image_seed="jhumka-pair",
    ),
    seed_product(
        category_id="jewellery-accessories",
        brand_id="veloura",
        name="Pearl Drop Earrings",
        slug="pearl-drop-earrings",
        short_description="Elegant pearl drops for subtle dressing",
        description="A polished pair of earrings with pearl accents and easy day-to-night styling.",
        variant_name="One Size / Pearl",
        sku="ERNG-PEARL-DROP-OS",
        price="249.00",
        quantity_available=57,
        image_seed="pearl-earrings",
    ),
    seed_product(
        category_id="jewellery-accessories",
        brand_id="veloura",
        name="Minimal Bracelet Stack",
        slug="minimal-bracelet-stack",
        short_description="Delicate bracelet stack set of 3",
        description="A slim, modern bracelet set designed for daily layering.",
        variant_name="One Size / Gold",
        sku="BRC-STACK-GOLD-OS",
        price="229.00",
        quantity_available=69,
        image_seed="bracelet-stack",
    ),
    seed_product(
        category_id="home-decor",
        brand_id="housebloom",
        name="Ceramic Vase Duo",
        slug="ceramic-vase-duo",
        short_description="Neutral ceramic vases for shelf styling",
        description="A two-piece vase set designed to elevate consoles, corners, and center tables.",
        variant_name="Set of 2 / Sand",
        sku="VASE-DUO-SAND-2",
        price="649.00",
        quantity_available=24,
        image_seed="ceramic-vase",
    ),
    seed_product(
        category_id="home-decor",
        brand_id="housebloom",
        name="LED Floating Diya Lamp",
        slug="led-floating-diya-lamp",
        short_description="Decorative diya lamp with warm glow",
        description="Festive ambient lighting for entryways, pooja spaces, and gifting.",
        variant_name="Set of 4 / Warm White",
        sku="DIYA-LED-WARM-4",
        price="399.00",
        quantity_available=46,
        image_seed="diya-lamp",
    ),
    seed_product(
        category_id="home-decor",
        brand_id="housebloom",
        name="Woven Storage Basket",
        slug="woven-storage-basket",
        short_description="Textured basket for tidy corners",
        description="A warm-toned woven basket that blends utility with living-room styling.",
        variant_name="Large / Natural",
        sku="BASKET-WOVEN-NAT-L",
        price="549.00",
        quantity_available=34,
        image_seed="storage-basket",
    ),
    seed_product(
        category_id="home-decor",
        brand_id="housebloom",
        name="Botanical Cushion Cover Set",
        slug="botanical-cushion-cover-set",
        short_description="Printed cushion cover set for a softer room look",
        description="Fresh botanical prints designed to brighten sofas, lounge chairs and beds.",
        variant_name="16x16 / Set of 5",
        sku="CUSHION-BOTANICAL-5",
        price="499.00",
        quantity_available=41,
        image_seed="cushion-cover",
    ),
    seed_product(
        category_id="footwear",
        brand_id="urbanstitch",
        name="Everyday Flat Sandals",
        slug="everyday-flat-sandals",
        short_description="Comfort sandals with textured straps",
        description="Easy slip-on sandals made for long daily wear and simple styling.",
        variant_name="39 / Tan",
        sku="SANDAL-FLAT-TAN-39",
        price="599.00",
        quantity_available=52,
        image_seed="flat-sandals",
    ),
    seed_product(
        category_id="footwear",
        brand_id="urbanstitch",
        name="Chunky Street Sneakers",
        slug="chunky-street-sneakers",
        short_description="Modern sneakers with bold sole",
        description="Chunky everyday sneakers with cushioned comfort and a clean streetwear look.",
        variant_name="42 / White",
        sku="SNKR-CHUNKY-WHT-42",
        price="1399.00",
        quantity_available=19,
        image_seed="street-sneakers",
    ),
    seed_product(
        category_id="footwear",
        brand_id="urbanstitch",
        name="Minimal Slide Slippers",
        slug="minimal-slide-slippers",
        short_description="Soft slides for indoors and quick errands",
        description="Lightweight slip-ons with a minimal profile and all-day ease.",
        variant_name="41 / Black",
        sku="SLIDE-MIN-BLK-41",
        price="349.00",
        quantity_available=79,
        image_seed="slide-slippers",
    ),
    seed_product(
        category_id="footwear",
        brand_id="urbanstitch",
        name="Braided Heel Sandals",
        slug="braided-heel-sandals",
        short_description="Dressy sandals with comfortable block heel",
        description="An easy occasion heel with braided strap detailing and a stable fit.",
        variant_name="38 / Beige",
        sku="HEEL-BRAID-BGE-38",
        price="999.00",
        quantity_available=21,
        image_seed="heel-sandals",
    ),
    seed_product(
        category_id="bags",
        brand_id="housebloom",
        name="Structured Tote Bag",
        slug="structured-tote-bag",
        short_description="Daily tote with clean silhouette and roomy interior",
        description="A polished tote bag built for office essentials, daily carry and quick travel.",
        variant_name="Large / Beige",
        sku="TOTE-STRUCT-BEIGE-L",
        price="899.00",
        quantity_available=37,
        image_seed="structured-tote",
    ),
    seed_product(
        category_id="bags",
        brand_id="housebloom",
        name="Quilted Sling Bag",
        slug="quilted-sling-bag",
        short_description="Compact sling with quilted finish",
        description="A small quilted sling designed for everyday styling and light carrying.",
        variant_name="One Size / Black",
        sku="SLING-QUILT-BLK-OS",
        price="749.00",
        quantity_available=42,
        image_seed="quilted-sling",
    ),
    seed_product(
        category_id="bags",
        brand_id="housebloom",
        name="Canvas Shopper Tote",
        slug="canvas-shopper-tote",
        short_description="Large canvas tote for errands and college",
        description="A roomy canvas shopper designed for practical use without losing a clean look.",
        variant_name="One Size / Olive",
        sku="TOTE-CANVAS-OLV-OS",
        price="529.00",
        quantity_available=58,
        image_seed="canvas-shopper",
    ),
    seed_product(
        category_id="bags",
        brand_id="housebloom",
        name="Mini Vanity Crossbody",
        slug="mini-vanity-crossbody",
        short_description="Compact crossbody with structured case shape",
        description="A polished mini bag that adds sharp structure to a casual or occasion outfit.",
        variant_name="One Size / Tan",
        sku="BAG-VANITY-TAN-OS",
        price="679.00",
        quantity_available=35,
        image_seed="mini-vanity-bag",
    ),
]
